/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { Instance } from '../model';
/**
 * InstancesApi - axios parameter creator
 * @export
 */
export const InstancesApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Adds a new instance represented by the passed Object.
         * @summary Add an instance
         * @param {Instance} instance the instance to add
         * @param {boolean} [waitFor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        add1: async (instance: Instance, waitFor?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('add1', 'instance', instance)
            const localVarPath = `/recordm/instances`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (waitFor !== undefined) {
                localVarQueryParameter['waitFor'] = waitFor;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Adds a LogM log entry to an instance.
         * @summary Add log to instance
         * @param {number} id The instance id
         * @param {string} [body] The log message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLogMessageToInstance1: async (id: number, body?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('addLogMessageToInstance1', 'id', id)
            const localVarPath = `/recordm/instances/{id}/log`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Deletes an instance.
         * @summary Delete an instance
         * @param {number} id The id of the instance to delete
         * @param {boolean} [ignoreRefs] If ignoreRefs is true, then the instance will be deleted even if other instances are referencing it. Otherwise an error will be returned if there are instances with a reference to it. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1: async (id: number, ignoreRefs?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('delete1', 'id', id)
            const localVarPath = `/recordm/instances/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (ignoreRefs !== undefined) {
                localVarQueryParameter['ignoreRefs'] = ignoreRefs;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Download a file that is attached to a $file field
         * @summary Download file from field in instance
         * @param {string} id The id of the instance
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {string} filename The filename of the file to download.
         * @param {string} [disposition] The Content-Disposition to use when downloading the file. Only useful when used as link in a webpage, to control if it should be downloaded or shown inline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile1: async (id: string, fieldDefinitionId: string, filename: string, disposition?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('downloadFile1', 'id', id)
            // verify required parameter 'fieldDefinitionId' is not null or undefined
            assertParamExists('downloadFile1', 'fieldDefinitionId', fieldDefinitionId)
            // verify required parameter 'filename' is not null or undefined
            assertParamExists('downloadFile1', 'filename', filename)
            const localVarPath = `/recordm/instances/{id}/files/{fieldDefinitionId}/{filename}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"fieldDefinitionId"}}`, encodeURIComponent(String(fieldDefinitionId)))
                .replace(`{${"filename"}}`, encodeURIComponent(String(filename)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (disposition !== undefined) {
                localVarQueryParameter['disposition'] = disposition;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtains a representation of an instance.
         * @summary Get an instance
         * @param {number} id 
         * @param {string} [ifNoneMatch] If a value is given, it will be compared to the current version of the instance and if they are equal, a 304 will be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstance1: async (id: number, ifNoneMatch?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getInstance1', 'id', id)
            const localVarPath = `/recordm/instances/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (ifNoneMatch !== undefined && ifNoneMatch !== null) {
                localVarHeaderParameter['If-None-Match'] = String(ifNoneMatch);
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Obtains a representation of an instance with no values. Useful for using as a starting point for creating a new instance.
         * @summary Get a new empty instance
         * @param {number} definitionId The id of the definition of which we want the empty instance.
         * @param {boolean} [withDefaults] If true, all the fields with defined default values will have them already filled. If false, all the fields will have empty values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewInstance1: async (definitionId: number, withDefaults?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'definitionId' is not null or undefined
            assertParamExists('getNewInstance1', 'definitionId', definitionId)
            const localVarPath = `/recordm/instances/empty/definition/{definitionId}`
                .replace(`{${"definitionId"}}`, encodeURIComponent(String(definitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (withDefaults !== undefined) {
                localVarQueryParameter['withDefaults'] = withDefaults;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Updates an instance with the complete representation passed.
         * @summary Update an instance
         * @param {number} id The id of the instance to update
         * @param {Instance} instance the updated instance
         * @param {boolean} [acceptOutdated] Should outdated $extRef fields be accepted?
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2: async (id: number, instance: Instance, acceptOutdated?: boolean, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('update2', 'id', id)
            // verify required parameter 'instance' is not null or undefined
            assertParamExists('update2', 'instance', instance)
            const localVarPath = `/recordm/instances/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication cobtoken required

            if (acceptOutdated !== undefined) {
                localVarQueryParameter['acceptOutdated'] = acceptOutdated;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(instance, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile: async (id: string, fieldDefinitionId: string, file?: object, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('uploadFile', 'id', id)
            // verify required parameter 'fieldDefinitionId' is not null or undefined
            assertParamExists('uploadFile', 'fieldDefinitionId', fieldDefinitionId)
            const localVarPath = `/recordm/instances/{id}/files/{fieldDefinitionId}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"fieldDefinitionId"}}`, encodeURIComponent(String(fieldDefinitionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication cobtoken required


            if (file !== undefined) { 
                localVarFormParams.append('file', new Blob([JSON.stringify(file)], { type: "application/json", }));
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionIdOrName The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile1: async (id: string, fieldDefinitionIdOrName: string, file?: object, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('uploadFile1', 'id', id)
            // verify required parameter 'fieldDefinitionIdOrName' is not null or undefined
            assertParamExists('uploadFile1', 'fieldDefinitionIdOrName', fieldDefinitionIdOrName)
            const localVarPath = `/recordm/instances/{id}/files/{fieldDefinitionIdOrName}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"fieldDefinitionIdOrName"}}`, encodeURIComponent(String(fieldDefinitionIdOrName)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            // authentication cobtoken required


            if (file !== undefined) { 
                localVarFormParams.append('file', new Blob([JSON.stringify(file)], { type: "application/json", }));
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InstancesApi - functional programming interface
 * @export
 */
export const InstancesApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InstancesApiAxiosParamCreator(configuration)
    return {
        /**
         * Adds a new instance represented by the passed Object.
         * @summary Add an instance
         * @param {Instance} instance the instance to add
         * @param {boolean} [waitFor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async add1(instance: Instance, waitFor?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.add1(instance, waitFor, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Adds a LogM log entry to an instance.
         * @summary Add log to instance
         * @param {number} id The instance id
         * @param {string} [body] The log message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async addLogMessageToInstance1(id: number, body?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.addLogMessageToInstance1(id, body, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Deletes an instance.
         * @summary Delete an instance
         * @param {number} id The id of the instance to delete
         * @param {boolean} [ignoreRefs] If ignoreRefs is true, then the instance will be deleted even if other instances are referencing it. Otherwise an error will be returned if there are instances with a reference to it. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete1(id: number, ignoreRefs?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete1(id, ignoreRefs, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Download a file that is attached to a $file field
         * @summary Download file from field in instance
         * @param {string} id The id of the instance
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {string} filename The filename of the file to download.
         * @param {string} [disposition] The Content-Disposition to use when downloading the file. Only useful when used as link in a webpage, to control if it should be downloaded or shown inline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadFile1(id: string, fieldDefinitionId: string, filename: string, disposition?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadFile1(id, fieldDefinitionId, filename, disposition, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Obtains a representation of an instance.
         * @summary Get an instance
         * @param {number} id 
         * @param {string} [ifNoneMatch] If a value is given, it will be compared to the current version of the instance and if they are equal, a 304 will be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInstance1(id: number, ifNoneMatch?: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInstance1(id, ifNoneMatch, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Obtains a representation of an instance with no values. Useful for using as a starting point for creating a new instance.
         * @summary Get a new empty instance
         * @param {number} definitionId The id of the definition of which we want the empty instance.
         * @param {boolean} [withDefaults] If true, all the fields with defined default values will have them already filled. If false, all the fields will have empty values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNewInstance1(definitionId: number, withDefaults?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNewInstance1(definitionId, withDefaults, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Updates an instance with the complete representation passed.
         * @summary Update an instance
         * @param {number} id The id of the instance to update
         * @param {Instance} instance the updated instance
         * @param {boolean} [acceptOutdated] Should outdated $extRef fields be accepted?
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update2(id: number, instance: Instance, acceptOutdated?: boolean, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update2(id, instance, acceptOutdated, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile(id: string, fieldDefinitionId: string, file?: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile(id, fieldDefinitionId, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionIdOrName The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadFile1(id: string, fieldDefinitionIdOrName: string, file?: object, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadFile1(id, fieldDefinitionIdOrName, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * InstancesApi - factory interface
 * @export
 */
export const InstancesApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InstancesApiFp(configuration)
    return {
        /**
         * Adds a new instance represented by the passed Object.
         * @summary Add an instance
         * @param {Instance} instance the instance to add
         * @param {boolean} [waitFor] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        add1(instance: Instance, waitFor?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.add1(instance, waitFor, options).then((request) => request(axios, basePath));
        },
        /**
         * Adds a LogM log entry to an instance.
         * @summary Add log to instance
         * @param {number} id The instance id
         * @param {string} [body] The log message
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        addLogMessageToInstance1(id: number, body?: string, options?: any): AxiosPromise<void> {
            return localVarFp.addLogMessageToInstance1(id, body, options).then((request) => request(axios, basePath));
        },
        /**
         * Deletes an instance.
         * @summary Delete an instance
         * @param {number} id The id of the instance to delete
         * @param {boolean} [ignoreRefs] If ignoreRefs is true, then the instance will be deleted even if other instances are referencing it. Otherwise an error will be returned if there are instances with a reference to it. 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete1(id: number, ignoreRefs?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.delete1(id, ignoreRefs, options).then((request) => request(axios, basePath));
        },
        /**
         * Download a file that is attached to a $file field
         * @summary Download file from field in instance
         * @param {string} id The id of the instance
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {string} filename The filename of the file to download.
         * @param {string} [disposition] The Content-Disposition to use when downloading the file. Only useful when used as link in a webpage, to control if it should be downloaded or shown inline.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadFile1(id: string, fieldDefinitionId: string, filename: string, disposition?: string, options?: any): AxiosPromise<void> {
            return localVarFp.downloadFile1(id, fieldDefinitionId, filename, disposition, options).then((request) => request(axios, basePath));
        },
        /**
         * Obtains a representation of an instance.
         * @summary Get an instance
         * @param {number} id 
         * @param {string} [ifNoneMatch] If a value is given, it will be compared to the current version of the instance and if they are equal, a 304 will be returned.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInstance1(id: number, ifNoneMatch?: string, options?: any): AxiosPromise<void> {
            return localVarFp.getInstance1(id, ifNoneMatch, options).then((request) => request(axios, basePath));
        },
        /**
         * Obtains a representation of an instance with no values. Useful for using as a starting point for creating a new instance.
         * @summary Get a new empty instance
         * @param {number} definitionId The id of the definition of which we want the empty instance.
         * @param {boolean} [withDefaults] If true, all the fields with defined default values will have them already filled. If false, all the fields will have empty values.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNewInstance1(definitionId: number, withDefaults?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.getNewInstance1(definitionId, withDefaults, options).then((request) => request(axios, basePath));
        },
        /**
         * Updates an instance with the complete representation passed.
         * @summary Update an instance
         * @param {number} id The id of the instance to update
         * @param {Instance} instance the updated instance
         * @param {boolean} [acceptOutdated] Should outdated $extRef fields be accepted?
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update2(id: number, instance: Instance, acceptOutdated?: boolean, options?: any): AxiosPromise<void> {
            return localVarFp.update2(id, instance, acceptOutdated, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionId The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile(id: string, fieldDefinitionId: string, file?: object, options?: any): AxiosPromise<void> {
            return localVarFp.uploadFile(id, fieldDefinitionId, file, options).then((request) => request(axios, basePath));
        },
        /**
         * Upload a file to be used as a value for a $file field
         * @summary Upload file to field in instance
         * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
         * @param {string} fieldDefinitionIdOrName The id of the field definition of the $file field
         * @param {object} [file] The file to upload.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadFile1(id: string, fieldDefinitionIdOrName: string, file?: object, options?: any): AxiosPromise<void> {
            return localVarFp.uploadFile1(id, fieldDefinitionIdOrName, file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InstancesApi - object-oriented interface
 * @export
 * @class InstancesApi
 * @extends {BaseAPI}
 */
export class InstancesApi extends BaseAPI {
    /**
     * Adds a new instance represented by the passed Object.
     * @summary Add an instance
     * @param {Instance} instance the instance to add
     * @param {boolean} [waitFor] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public add1(instance: Instance, waitFor?: boolean, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).add1(instance, waitFor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Adds a LogM log entry to an instance.
     * @summary Add log to instance
     * @param {number} id The instance id
     * @param {string} [body] The log message
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public addLogMessageToInstance1(id: number, body?: string, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).addLogMessageToInstance1(id, body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes an instance.
     * @summary Delete an instance
     * @param {number} id The id of the instance to delete
     * @param {boolean} [ignoreRefs] If ignoreRefs is true, then the instance will be deleted even if other instances are referencing it. Otherwise an error will be returned if there are instances with a reference to it. 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public delete1(id: number, ignoreRefs?: boolean, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).delete1(id, ignoreRefs, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Download a file that is attached to a $file field
     * @summary Download file from field in instance
     * @param {string} id The id of the instance
     * @param {string} fieldDefinitionId The id of the field definition of the $file field
     * @param {string} filename The filename of the file to download.
     * @param {string} [disposition] The Content-Disposition to use when downloading the file. Only useful when used as link in a webpage, to control if it should be downloaded or shown inline.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public downloadFile1(id: string, fieldDefinitionId: string, filename: string, disposition?: string, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).downloadFile1(id, fieldDefinitionId, filename, disposition, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtains a representation of an instance.
     * @summary Get an instance
     * @param {number} id 
     * @param {string} [ifNoneMatch] If a value is given, it will be compared to the current version of the instance and if they are equal, a 304 will be returned.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public getInstance1(id: number, ifNoneMatch?: string, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).getInstance1(id, ifNoneMatch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Obtains a representation of an instance with no values. Useful for using as a starting point for creating a new instance.
     * @summary Get a new empty instance
     * @param {number} definitionId The id of the definition of which we want the empty instance.
     * @param {boolean} [withDefaults] If true, all the fields with defined default values will have them already filled. If false, all the fields will have empty values.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public getNewInstance1(definitionId: number, withDefaults?: boolean, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).getNewInstance1(definitionId, withDefaults, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates an instance with the complete representation passed.
     * @summary Update an instance
     * @param {number} id The id of the instance to update
     * @param {Instance} instance the updated instance
     * @param {boolean} [acceptOutdated] Should outdated $extRef fields be accepted?
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public update2(id: number, instance: Instance, acceptOutdated?: boolean, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).update2(id, instance, acceptOutdated, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a file to be used as a value for a $file field
     * @summary Upload file to field in instance
     * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
     * @param {string} fieldDefinitionId The id of the field definition of the $file field
     * @param {object} [file] The file to upload.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public uploadFile(id: string, fieldDefinitionId: string, file?: object, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).uploadFile(id, fieldDefinitionId, file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Upload a file to be used as a value for a $file field
     * @summary Upload file to field in instance
     * @param {string} id When uploading to an existing instance, it\&#39;s the id of the instance. When uploading for an instance that doesn\&#39;t yet exist, it should be an UUID that matches the one the instance will have on creation. This way the already uploaded files will be moved to the final destination.
     * @param {string} fieldDefinitionIdOrName The id of the field definition of the $file field
     * @param {object} [file] The file to upload.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InstancesApi
     */
    public uploadFile1(id: string, fieldDefinitionIdOrName: string, file?: object, options?: AxiosRequestConfig) {
        return InstancesApiFp(this.configuration).uploadFile1(id, fieldDefinitionIdOrName, file, options).then((request) => request(this.axios, this.basePath));
    }
}
