/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldDefinition } from "./field-definition"

/**
 *
 * @export
 * @interface CreateDefinitionRequest
 */
export interface CreateDefinitionRequest {
  /**
   *
   * @type {string}
   * @memberof CreateDefinitionRequest
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof CreateDefinitionRequest
   */
  description?: string
  /**
   *
   * @type {boolean}
   * @memberof CreateDefinitionRequest
   */
  duplicable?: boolean
  /**
   *
   * @type {Array<FieldDefinition>}
   * @memberof CreateDefinitionRequest
   */
  fieldDefinitions?: Array<FieldDefinition>
}
