/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Definition } from './definition';
import { DomainLinks } from './domain-links';

/**
 * 
 * @export
 * @interface DecoratedDomain
 */
export interface DecoratedDomain {
    /**
     * 
     * @type {number}
     * @memberof DecoratedDomain
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof DecoratedDomain
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof DecoratedDomain
     */
    'description'?: string;
    /**
     * 
     * @type {Array<Definition>}
     * @memberof DecoratedDomain
     */
    'definitions'?: Array<Definition>;
    /**
     * 
     * @type {number}
     * @memberof DecoratedDomain
     */
    'version'?: number;
    /**
     * 
     * @type {DomainLinks}
     * @memberof DecoratedDomain
     */
    '_links'?: DomainLinks;
}

