/* tslint:disable */
/* eslint-disable */

/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DefinitionLinks
 */
export interface DefinitionLinks {
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  update?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  export: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  clone?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  disable?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  enable?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  instantiate?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  bulkRequest?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  updateInstances?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  delete?: string
  /**
   *
   * @type {string}
   * @memberof DefinitionLinks
   */
  size: string
}
