/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Definition } from './definition';
import { Fields } from './fields';

/**
 * 
 * @export
 * @interface DefinitionStats
 */
export interface DefinitionStats {
    /**
     * 
     * @type {Definition}
     * @memberof DefinitionStats
     */
    'definition'?: Definition;
    /**
     * 
     * @type {Fields}
     * @memberof DefinitionStats
     */
    'fields'?: Fields;
    /**
     * 
     * @type {number}
     * @memberof DefinitionStats
     */
    'instances_on_db'?: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionStats
     */
    'instances_on_es'?: number;
    /**
     * 
     * @type {number}
     * @memberof DefinitionStats
     */
    'es_errors'?: number;
}

