/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DomainLinks
 */
export interface DomainLinks {
    /**
     * 
     * @type {string}
     * @memberof DomainLinks
     */
    'update'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLinks
     */
    'delete'?: string;
    /**
     * 
     * @type {string}
     * @memberof DomainLinks
     */
    'size': string;
}

