/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FieldDefinition
 */
export interface FieldDefinition {
    /**
     * 
     * @type {number}
     * @memberof FieldDefinition
     */
    'id'?: number;
    /**
     * 
     * @type {string}
     * @memberof FieldDefinition
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldDefinition
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldDefinition
     */
    'condition'?: string;
    /**
     * 
     * @type {string}
     * @memberof FieldDefinition
     */
    'required'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof FieldDefinition
     */
    'duplicable'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof FieldDefinition
     */
    'groupField'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof FieldDefinition
     */
    'order'?: number;
    /**
     * 
     * @type {Array<FieldDefinition>}
     * @memberof FieldDefinition
     */
    'fields'?: Array<FieldDefinition>;
}

