/* tslint:disable */
/* eslint-disable */

/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Fields
 */
export interface Fields {
  /**
   *
   * @type {number}
   * @memberof Fields
   */
  count?: number
  /**
   *
   * @type {number}
   * @memberof Fields
   */
  $refs?: number
  /**
   *
   * @type {number}
   * @memberof Fields
   */
  $extRefs?: number
}
