/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { FieldDefinition } from './field-definition';
import { Task } from './task';

/**
 * 
 * @export
 * @interface InstanceField
 */
export interface InstanceField {
    /**
     * 
     * @type {number}
     * @memberof InstanceField
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof InstanceField
     */
    'parent'?: number;
    /**
     * 
     * @type {FieldDefinition}
     * @memberof InstanceField
     */
    'fieldDefinition': FieldDefinition;
    /**
     * 
     * @type {string}
     * @memberof InstanceField
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof InstanceField
     */
    'label': string;
    /**
     * 
     * @type {Array<Task>}
     * @memberof InstanceField
     */
    'tasks'?: Array<Task>;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof InstanceField
     */
    'permissions'?: { [key: string]: boolean; };
    /**
     * 
     * @type {boolean}
     * @memberof InstanceField
     */
    'duplicate': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InstanceField
     */
    'off': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InstanceField
     */
    'upToDate': boolean;
}

