/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Definition } from './definition';
import { InstanceField } from './instance-field';

/**
 * 
 * @export
 * @interface Instance
 */
export interface Instance {
    /**
     * 
     * @type {number}
     * @memberof Instance
     */
    'id': number;
    /**
     * The relative path for the Instance\'s attached files. Normally the id of the instance.
     * @type {string}
     * @memberof Instance
     */
    'attachmentPath'?: string;
    /**
     * 
     * @type {number}
     * @memberof Instance
     */
    'version': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof Instance
     */
    'instanceLabel': Array<string>;
    /**
     * 
     * @type {Definition}
     * @memberof Instance
     */
    'jsonDefinition': Definition;
    /**
     * 
     * @type {Array<InstanceField>}
     * @memberof Instance
     */
    'fields'?: Array<InstanceField>;
}

