/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface IntegrationUpdateMessage
 */
export interface IntegrationUpdateMessage {
    /**
     * The name of the Definition of the instances we are updating.
     * @type {string}
     * @memberof IntegrationUpdateMessage
     */
    'type': string;
    /**
     * A condition to match the instances to update. Can be either an ES query string, or the special value \"recordmInstanceId:N[@V]\" to match a single instance. If the optional \'@V\' is used, the update will only take place if the instance N is at version V.
     * @type {string}
     * @memberof IntegrationUpdateMessage
     */
    'condition': string;
    /**
     * An object in which the keys are the field IDs or field paths, and the values are the values to be used to fill the fields.
     * @type {object}
     * @memberof IntegrationUpdateMessage
     */
    'values': object;
}

