/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { TaskAssignee } from './task-assignee';

/**
 * 
 * @export
 * @interface Task
 */
export interface Task {
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'state'?: TaskStateEnum;
    /**
     * 
     * @type {TaskAssignee}
     * @memberof Task
     */
    'assignee'?: TaskAssignee;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Task
     */
    'correlationId'?: string;
    /**
     * 
     * @type {{ [key: string]: boolean; }}
     * @memberof Task
     */
    'permissions'?: { [key: string]: boolean; };
}

export const TaskStateEnum = {
    TODO: 'TODO',
    COMPLETE: 'COMPLETE',
    PLANNED: 'PLANNED'
} as const;

export type TaskStateEnum = typeof TaskStateEnum[keyof typeof TaskStateEnum];


