/* tslint:disable */
/* eslint-disable */
/**
 * RecordM API
 * The RecordM REST API<br/><br/> **Note**: To  use the \'Try it out\' buttons, you must be [logged in](/).
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FieldDefinition } from "./field-definition"

/**
 *
 * @export
 * @interface UpdateDefinitionRequest
 */
export interface UpdateDefinitionRequest {
  /**
   *
   * @type {string}
   * @memberof UpdateDefinitionRequest
   */
  name: string
  /**
   *
   * @type {string}
   * @memberof UpdateDefinitionRequest
   */
  description?: string
  /**
   *
   * @type {boolean}
   * @memberof UpdateDefinitionRequest
   */
  duplicable?: boolean
  /**
   *
   * @type {string}
   * @memberof UpdateDefinitionRequest
   */
  state?: UpdateDefinitionRequestStateEnum
  /**
   *
   * @type {Array<FieldDefinition>}
   * @memberof UpdateDefinitionRequest
   */
  fieldDefinitions?: Array<FieldDefinition>
  /**
   *
   * @type {number}
   * @memberof UpdateDefinitionRequest
   */
  version: number
}

export const UpdateDefinitionRequestStateEnum = {
  ENABLED: "enabled",
  DISABLED: "disabled",
  DELETE_IN_PROGRESS: "deleteInProgress",
} as const

export type UpdateDefinitionRequestStateEnum =
  typeof UpdateDefinitionRequestStateEnum[keyof typeof UpdateDefinitionRequestStateEnum]
